public with sharing class DataMgmtController {

    public PageReference ExternalWebServiceBatchClear() {
        return null;
    }


    public String isWebserviceStarted { get; set; }

    public PageReference ExternalWebServiceBatchSetup() {
        return null;
    }


    public PageReference clearBroadCastMessage() {
        return null;
    }


    public PageReference createBroadCastMessage() {
        return null;
    }


    public String broadcastEg { get; set; }

    public String boardcastMsg { get; set; }

    public PageReference initDataMgmtController() {
        return null;
    }

}